spring.application.name=music-streaming

spring.datasource.url=jdbc:h2:mem:streaming

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=atddd

spring.datasource.password=teste

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.h2.console.enabled=true

server.port=8081